spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zytshixun
    username: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
